# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://jhipster.github.io/profiles/
# More information on configuration properties: https://jhipster.github.io/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    devtools:
        restart:
            enabled: true
            exclude: .h2.server.properties,static/**,templates/**
        livereload:
            enabled: false # we use gulp + BrowserSync for livereload
    jackson:
        serialization.indent_output: true
    datasource:
        url: jdbc:hsqldb:mem:managementportal;DB_CLOSE_DELAY=-1
        username: ManagementPortal
        password:
    h2:
        console:
            enabled: false
    jpa:
        database-platform: org.hibernate.dialect.HSQLDialect
        database: HSQL
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
            hibernate.cache.hazelcast.instance_name: ManagementPortal
            hibernate.cache.use_minimal_puts: true
            hibernate.cache.hazelcast.use_lite_member: true
            hibernate.ddl-auto: none
    mail:
        host:  # for hotmail
        port:
        username: user@example.com
        password: XXXXXXXX
        protocol: smtp
        properties.mail.smtp:
            auth: true
            starttls.enable: true
            ssl.trust:  # for hotmail
    thymeleaf:
        cache: false
    liquibase:
        contexts: dev

# ===================================================================
# To enable SSL, generate a certificate using:
# keytool -genkey -alias ManagementPortal -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore src/main/resources/config/keystore.p12 -validity 3650
#
# You can also use Let's Encrypt:
# https://maximilian-boehm.com/hp2121/Create-a-Java-Keystore-JKS-from-Let-s-Encrypt-Certificates.htm
#
# Then, modify the server.ssl properties so your "server" configuration looks like:
#
# server:
#    port: 8443
#    ssl:
#        key-store: src/main/resources/config/keystore.p12
#        key-store-password: <your-password>
#        keyStoreType: PKCS12
#        keyAlias: ManagementPortal
# ===================================================================
server:
    port: 8080
    servlet:
      session.cookie.secure: false
      context-path: /managementportal
      session:
        cookie:
          path: /



# ===================================================================
# ManagementPortal specific properties
#
# ===================================================================
managementportal:
    common:
        baseUrl: http://localhost:8080 # Modify according to your server's URL
        managementPortalBaseUrl: http://localhost:8080/managementportal
        privacyPolicyUrl: http://info.thehyve.nl/radar-cns-privacy-policy
        adminPassword: admin
        activationKeyTimeoutInSeconds: 86400 # 1 day
    mail: # specific ManagementPortal mail property, for standard properties see MailProperties
        from: ManagementPortal@localhost
    frontend:
        clientId: ManagementPortalapp
        clientSecret: my-secret-token-to-change-in-production
        accessTokenValiditySeconds: 14400
        refreshTokenValiditySeconds: 259200
        sessionTimeout : 86400 # session for rft cookie
    oauth:
        clientsFile: src/main/docker/etc/config/oauth_client_details.csv
        metaTokenTimeout: PT1H #timeout should be specified as the ISO-8601 duration format {@code PnDTnHnMn.nS}.
        persistentMetaTokenTimeout: P31D #timeout should be specified as the ISO-8601 duration format {@code PnDTnHnMn.nS}.
    catalogueServer:
        enableAutoImport: false
        serverUrl:
    siteSettings:
        # The line below can be uncommented to add some hidden fields for UI testing
        #hiddenSubjectFields: [person_name, date_of_birth, group]
    identityServer:
        serverUrl: http://localhost:4433
        serverAdminUrl: http://localhost:4434

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://jhipster.github.io/common-application-properties/
# ===================================================================

jhipster:
    cache: # Cache configuration
        hazelcast: # Hazelcast distributed cache
            time-to-live-seconds: 3600
            backup-count: 1
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queue-size: 512

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://jhipster.github.io/common-application-properties/
# ===================================================================


application:
