version: '2'
services:
    managementportal-app:
        image: managementportal
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://managementportal-mysql:3306/managementportal?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    managementportal-mysql:
        extends:
            file: mysql.yml
            service: managementportal-mysql
