version: '2'
services:
    managementportal-app:
        build:
            context: ../../../
            dockerfile: ./Dockerfile
        environment:
            - SPRING_PROFILES_ACTIVE=prod,api-docs
            - SPRING_DATASOURCE_URL=jdbc:postgresql://managementportal-postgresql:5432/managementportal
            - SPRING_DATASOURCE_USERNAME=radarbase
            - SPRING_DATASOURCE_PASSWORD=radarbase
            - MANAGEMENTPORTAL_FRONTEND_CLIENT_SECRET=secret
            - MANAGEMENTPORTAL_IDENTITYSERVER_ADMINEMAIL=admin-email-here@radar-base.net
            - MANAGEMENTPORTAL_IDENTITYSERVER_SERVERURL=http://kratos:4433
            - MANAGEMENTPORTAL_IDENTITYSERVER_LOGINURL=http://radar-self-enrolment-ui:3000
            - MANAGEMENTPORTAL_IDENTITYSERVER_SERVERADMINURL=http://kratos:4434
            - MANAGEMENTPORTAL_AUTHSERVER_SERVERURL=http://hydra:4444
            - MANAGEMENTPORTAL_AUTHSERVER_SERVERADMINURL=http://hydra:4445
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - JAVA_OPTS=-Xmx512m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 #enables remote debugging
        ports:
            - "8080:8080"
        volumes:
            - ./etc:/mp-includes
