version: '2'
services:
    managementportal-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/ManagementPortal/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=ManagementPortal
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
