version: '2'
services:
    postgresql:
        image: postgres:11-alpine
        environment:
            - POSTGRES_USER=radarbase
            - POSTGRES_PASSWORD=radarbase
            - POSTGRES_DB=managementportal
        ports:
            - "5432:5432"
